# Generated by Django 4.0.8 on 2023-11-06 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_remove_ads_image_adsimage_ads'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adsimage',
            name='ads',
        ),
        migrations.RemoveField(
            model_name='adsimage',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='adsimage',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='adsimage',
            name='ad',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ads.ads'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adsimage',
            name='image',
            field=models.ImageField(upload_to='ads_images'),
        ),
    ]
