# Generated by Django 4.0.8 on 2023-11-06 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_remove_adsimage_ads_remove_adsimage_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adsimage',
            name='ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='ads.ads'),
        ),
    ]
