# Generated by Django 4.0.8 on 2023-11-06 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='category_attributes/')),
                ('type', models.CharField(choices=[('integer', 'Integer'), ('button', 'Button'), ('select', 'Select'), ('multiselect', 'Multiselect')], default='integer', max_length=255)),
                ('filter_type', models.CharField(choices=[('range', 'Range'), ('multiselect', 'Multiselect')], default='range', max_length=255)),
                ('is_required', models.BooleanField(default=False)),
                ('is_list', models.BooleanField(default=False)),
                ('is_filter', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='AttributeOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='attribute.attribute')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
    ]
